package com.example.friendscharactersrecycleview;

public class MyData {

    static String[] nameArray={ "Joey Tribbiani","Rachel Green","Monica Geller","Ross Geller","Chandler Bing","Phoebe Buffay","Ursula Buffay","Janice Litman Goralnik","Gunther","Mike Hannigan","Jack Geller"};
    static String[] descriptionArray={"Played by Matt LeBlanc. A lovable and somewhat dim-witted struggling actor, Joey's charm lies in his loyalty to his friends and his endearing naivety when it comes to relationships. He's known for his catchphrase \"How you doin'?\" and his passion for food, particularly sandwiches.",
    "Played by Jennifer Aniston. Initially introduced as a spoiled daddy's girl, Rachel evolves throughout the series into a strong, independent woman pursuing her career in fashion. Her on-again, off-again romance with Ross remains a central storyline, as does her growth from a waitress at Central Perk to a successful executive at Ralph Lauren.",
    "Played by Courteney Cox. The perfectionist chef of the group, Monica is obsessive about cleanliness and organization, often providing comedic moments with her competitive nature and need for control. Despite her bossy tendencies, she's fiercely protective of her friends and has a soft spot for romance, especially when it comes to her on-again, off-again relationship with Chandler.",
    "Played by David Schwimmer. A paleontologist with a penchant for getting divorced, Ross is known for his awkwardness in social situations and his hopeless romanticism. His tumultuous love life, including his iconic relationship with Rachel, provides much of the series' drama and humor, along with his tendency to overanalyze and obsess over trivial matters.",
    "Played by Matthew Perry. Sardonic and sarcastic, Chandler uses humor as a defense mechanism, often masking his insecurities and fear of commitment. His job in statistical analysis and data reconfiguration is a constant source of jokes, as is his dysfunctional upbringing and complicated relationship with his father. Despite his sarcastic exterior, Chandler is fiercely loyal to his friends and ultimately finds happiness with Monica.",
    "Played by Lisa Kudrow. Eccentric and whimsical, Phoebe's quirky personality and unconventional upbringing lead to some of the show's most memorable moments, including her bizarre song lyrics and offbeat worldview. Her past, which includes living on the streets and being a surrogate mother for her half-brother's triplets, adds depth to her character, as does her spiritual beliefs and occasional psychic tendencies.",
    "Also portrayed by Lisa Kudrow. Phoebe's identical twin sister, Ursula is her polar opposite, often portrayed as selfish, promiscuous, and indifferent to others' feelings. She works as a waitress at Riff's, a seedy diner, and occasionally crosses paths with Phoebe, usually causing trouble or misunderstanding due to their similar appearance.",
    "Played by Maggie Wheeler. Recognizable by her grating voice and distinctive laugh, Janice is Chandler's on-again, off-again girlfriend throughout much of the series. Despite their tumultuous relationship, she remains a recurring character, often popping up at unexpected moments to deliver her trademark catchphrase, \"Oh. My. God!\"",
    "Played by James Michael Tyler. The eternally lovelorn barista at Central Perk, Gunther harbors a secret crush on Rachel throughout the series, though his feelings are mostly unrequited. His awkward interactions with the group, particularly Ross and Rachel, provide comedic relief, and his silent longing adds a touch of bittersweetness to the background of the show.",
    "Played by Paul Rudd. A sweet-natured and quirky musician who becomes Phoebe's love interest and eventual husband. Mike brings a grounded and sincere presence to the group, often serving as a foil to Phoebe's eccentricities.",
    "Played by Elliott Gould. Ross and Monica's father. Jack is a jovial and supportive figure in the lives of his children, often providing comedic relief with his endearing quirks and humorous anecdotes about their upbringing."};
    static int[] drawableArray={R.drawable.joey,R.drawable.rachel,R.drawable.monica,R.drawable.ross,R.drawable.chandler,R.drawable.phoebe,R.drawable.ursula,R.drawable.janice,R.drawable.gunther,R.drawable.mike,R.drawable.jack};
    static Integer[] id_={0,1,2,3,4,5,6,7,8,9,10};
}
